"""initial

Revision ID: 780ab0e87465
Revises: 
Create Date: 2026-05-20 22:09:34.731876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780ab0e87465'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashflow_entries',
    sa.Column('oid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('marketplace', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_cashflow_entries_entry_date'), 'cashflow_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_cashflow_entries_entry_type'), 'cashflow_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_cashflow_entries_marketplace'), 'cashflow_entries', ['marketplace'], unique=False)
    op.create_table('orders',
    sa.Column('oid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('marketplace', sa.String(length=16), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('logistics', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ad_spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_orders_marketplace'), 'orders', ['marketplace'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_orders_sale_date'), 'orders', ['sale_date'], unique=False)
    op.create_index(op.f('ix_orders_sku_id'), 'orders', ['sku_id'], unique=False)
    op.create_table('returns',
    sa.Column('oid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('marketplace', sa.String(length=16), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_returns_marketplace'), 'returns', ['marketplace'], unique=False)
    op.create_index(op.f('ix_returns_return_date'), 'returns', ['return_date'], unique=False)
    op.create_index(op.f('ix_returns_return_id'), 'returns', ['return_id'], unique=True)
    op.create_index(op.f('ix_returns_sku_id'), 'returns', ['sku_id'], unique=False)
    op.create_table('skus',
    sa.Column('oid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('marketplace', sa.String(length=16), nullable=False),
    sa.Column('cost_of_goods', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_skus_marketplace'), 'skus', ['marketplace'], unique=False)
    op.create_index(op.f('ix_skus_sku_id'), 'skus', ['sku_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skus_sku_id'), table_name='skus')
    op.drop_index(op.f('ix_skus_marketplace'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_returns_sku_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_return_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_return_date'), table_name='returns')
    op.drop_index(op.f('ix_returns_marketplace'), table_name='returns')
    op.drop_table('returns')
    op.drop_index(op.f('ix_orders_sku_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_sale_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_marketplace'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_cashflow_entries_marketplace'), table_name='cashflow_entries')
    op.drop_index(op.f('ix_cashflow_entries_entry_type'), table_name='cashflow_entries')
    op.drop_index(op.f('ix_cashflow_entries_entry_date'), table_name='cashflow_entries')
    op.drop_table('cashflow_entries')
    # ### end Alembic commands ###
